version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bat_trang_postgres
    restart: always
    ports:
      - '5433:5432' # Map port 5432 của container ra máy thật
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: battrang_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Giữ lại dữ liệu khi tắt Docker

volumes:
  postgres_data: