version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bat_trang_postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: battrang_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bat_trang_backend
    restart: always
    ports:
      - '6000:3000' # <--- SỬA DÒNG NÀY (Ngoài 6000 : Trong 3000)
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:password123@db:5432/battrang_db?schema=public"
      JWT_SECRET: "DayLaKhoaBiMatCuaDuAnBatTrangCeramics2024"
      PORT: 3000 # App vẫn chạy port 3000 bên trong container

volumes:
  postgres_data: